name: mobikul_rich_link_field_example
description: "Example project for demonstrating the mobikul_rich_link_field package."
publish_to: "none"

environment:
  sdk: ">=3.3.0 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  mobikul_rich_link_field:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0